### ISSUE TITLE
cmd/subd: hung update

### ISSUE THREAD

**Issue by masiulaniec** [Symantec/Dominator#420]
I cannot get a single `Subd.Update` to complete. Forcing the stack trace using `SIGQUIT` points at goroutine 37, which seems stuck reading from the ack channel:

```
$ sudo ~/bin/subd -alsoLogToStderr -logDir="" -rootDir /test -CAfile /etc/ssl/certs/DominatorCA.pem -initialLogDebugLevel 100
2018/02/21 08:00:12 Restoring CPU limit: 50%
2018/02/21 08:00:13 reverse listener: remember(127.0.0.1:39884): 0xc42000e040
2018/02/21 08:00:13 Update()


^\SIGQUIT: quit
PC=0x459b51 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0xb080a8, 0x0, 0x0, 0x0, 0x7ffe00000000, 0x43142a, 0x0, 0x0, 0x7ffe74f9b608, 0x41096b, ...)
	/home/vagrant/go/src/runtime/sys_linux_amd64.s:526 +0x21
runtime.futexsleep(0xb080a8, 0x7ffe00000000, 0xffffffffffffffff)
	/home/vagrant/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xb080a8)
	/home/vagrant/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stoplockedm()
	/home/vagrant/go/src/runtime/proc.go:2096 +0x8c
runtime.schedule()
	/home/vagrant/go/src/runtime/proc.go:2488 +0x2da
runtime.park_m(0xc420000180)
	/home/vagrant/go/src/runtime/proc.go:2599 +0xb6
runtime.mcall(0x0)
	/home/vagrant/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [sleep, locked to thread]:
time.Sleep(0x3b7dbe04)
	/home/vagrant/go/src/runtime/time.go:102 +0x166
github.com/Symantec/Dominator/sub/scanner.scannerDaemon(0xc420028640, 0x10, 0xc420022fa0, 0x1e, 0xc4201b1590, 0xc42017e720, 0x8eaea0, 0xc42002d470)
	/home/vagrant/src/github.com/Symantec/Dominator/sub/scanner/scand.go:43 +0x9d
github.com/Symantec/Dominator/sub/scanner.startScanning(0xc420028640, 0x10, 0xc420022fa0, 0x1e, 0xc4201b1590, 0x8eaea0, 0xc42002d470, 0xc42017ac00)
	/home/vagrant/src/github.com/Symantec/Dominator/sub/scanner/scand.go:32 +0x133
github.com/Symantec/Dominator/sub/scanner.StartScanning(0xc420028640, 0x10, 0xc420022fa0, 0x1e, 0xc4201b1590, 0x8eaea0, 0xc42002d470, 0xc42017ac00)
	/home/vagrant/src/github.com/Symantec/Dominator/sub/scanner/api.go:151 +0x77
main.main()
	/home/vagrant/src/github.com/Symantec/Dominator/cmd/subd/main.go:425 +0x964

goroutine 19 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/home/vagrant/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/home/vagrant/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/home/vagrant/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 4 [chan send, 2 minutes]:
github.com/Symantec/tricorder/go/tricorder.newIdSequence.func1(0xc42017e000)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:43 +0x41
created by github.com/Symantec/tricorder/go/tricorder.newIdSequence
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:40 +0x58

goroutine 5 [select, 2 minutes]:
github.com/Symantec/tricorder/go/tricorder.(*region).handleRequests(0xc420168280)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:185 +0xf0
github.com/Symantec/tricorder/go/tricorder.newRegion.func1(0xc420168280)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:143 +0x2b
created by github.com/Symantec/tricorder/go/tricorder.newRegion
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:142 +0x15a

goroutine 7 [select, 2 minutes]:
github.com/Symantec/tricorder/go/tricorder.(*region).handleRequests(0xc420169220)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:185 +0xf0
github.com/Symantec/tricorder/go/tricorder.newRegion.func1(0xc420169220)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:143 +0x2b
created by github.com/Symantec/tricorder/go/tricorder.newRegion
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:142 +0x15a

goroutine 8 [select, 2 minutes]:
github.com/Symantec/tricorder/go/tricorder.(*region).handleRequests(0xc420169270)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:185 +0xf0
github.com/Symantec/tricorder/go/tricorder.newRegion.func1(0xc420169270)
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:143 +0x2b
created by github.com/Symantec/tricorder/go/tricorder.newRegion
	/home/vagrant/src/github.com/Symantec/tricorder/go/tricorder/metric.go:142 +0x15a

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x7f06b0789e30, 0x72, 0xc4201d9268)
	/home/vagrant/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42017a198, 0x72, 0xffffffffffffff00, 0x8e5ec0, 0xac9638)
	/home/vagrant/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42017a198, 0xc4201a2800, 0x800, 0x800)
	/home/vagrant/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42017a180, 0xc4201a2800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42017a180, 0xc4201a2800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e040, 0xc4201a2800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc420090750, 0x7f06b074ad60, 0xc42000c100, 0x5, 0xc42000c100, 0x42aa64)
	/home/vagrant/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4201b2000, 0x8b0217, 0xc4201b2120, 0xc4201d9668)
	/home/vagrant/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4201b2000, 0xc420123000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).fill(0xc4200c6600)
	/home/vagrant/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).ReadSlice(0xc4200c6600, 0x1309c80a, 0xc4201d96c8, 0xc4201d96f8, 0x758ba0, 0xc4201b5628, 0x3fe433461309c800)
	/home/vagrant/go/src/bufio/bufio.go:341 +0x2c
bufio.(*Reader).ReadBytes(0xc4200c6600, 0x9a10a, 0x9a1db, 0xbe9b6b98c0ec5bd0, 0x220fb9d8f2, 0x0, 0x0)
	/home/vagrant/go/src/bufio/bufio.go:419 +0x6b
bufio.(*Reader).ReadString(0xc4200c6600, 0xa, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/bufio/bufio.go:459 +0x38
github.com/Symantec/Dominator/lib/srpc.handleConnection(0xc42006e440)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/srpc/server.go:370 +0x9f
github.com/Symantec/Dominator/lib/srpc.httpHandler(0x8e8780, 0xc4200201c0, 0xc420178c00, 0x1)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/srpc/server.go:324 +0x873
github.com/Symantec/Dominator/lib/srpc.tlsHttpHandler(0x8e8780, 0xc4200201c0, 0xc420178c00)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/srpc/server.go:220 +0x44
net/http.HandlerFunc.ServeHTTP(0x8af718, 0x8e8780, 0xc4200201c0, 0xc420178c00)
	/home/vagrant/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xb06e40, 0x8e8780, 0xc4200201c0, 0xc420178c00)
	/home/vagrant/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4201bbba0, 0x8e8780, 0xc4200201c0, 0xc420178c00)
	/home/vagrant/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42001e0a0, 0x8e8bc0, 0xc42006e100)
	/home/vagrant/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/home/vagrant/go/src/net/http/server.go:2795 +0x27b

goroutine 10 [select]:
main.main.func1(0xc42017e720, 0x8af768)
	/home/vagrant/src/github.com/Symantec/Dominator/cmd/subd/main.go:385 +0x8d3
created by github.com/Symantec/Dominator/sub/scanner.startScanning
	/home/vagrant/src/github.com/Symantec/Dominator/sub/scanner/scand.go:31 +0xd9

goroutine 11 [syscall, 2 minutes]:
syscall.Syscall6(0x120, 0x3, 0xc420050c90, 0xc420050c84, 0x80800, 0x0, 0x0, 0x1, 0x9, 0xc420050c40)
	/home/vagrant/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.accept4(0x3, 0xc420050c90, 0xc420050c84, 0x80800, 0xc420028520, 0xf, 0x10000000000000f)
	/home/vagrant/go/src/syscall/zsyscall_linux_amd64.go:1546 +0x7e
syscall.Accept4(0x3, 0x80800, 0x0, 0x0, 0x0, 0xc420050d90, 0x48589d)
	/home/vagrant/go/src/syscall/syscall_linux.go:454 +0x88
internal/poll.accept(0x3, 0x8af800, 0x0, 0x0, 0xc420070000, 0x7f06b07e9da8, 0x784f01, 0x10100c420028540)
	/home/vagrant/go/src/internal/poll/sock_cloexec.go:17 +0x3f
internal/poll.(*FD).Accept(0xc42017af80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/internal/poll/fd_unix.go:365 +0xd1
net.(*netFD).accept(0xc42017af80, 0x0, 0xc4200c7df8, 0x452940)
	/home/vagrant/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000e4c0, 0xc4200c7da0, 0xc420050fa8, 0x860c01)
	/home/vagrant/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000e4c0, 0xc420050fa8, 0xc42000e040, 0x7f06b074ab80, 0xc42000e040)
	/home/vagrant/go/src/net/tcpsock.go:259 +0x49
github.com/Symantec/Dominator/lib/net/reverseconnection.(*Listener).listen(0xc42009e3c0, 0xc4200c7da0)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/net/reverseconnection/listener.go:117 +0x49
created by github.com/Symantec/Dominator/lib/net/reverseconnection.listen
	/home/vagrant/src/github.com/Symantec/Dominator/lib/net/reverseconnection/listener.go:70 +0x1dc

goroutine 12 [chan receive, 2 minutes]:
github.com/Symantec/Dominator/lib/net/reverseconnection.(*Listener).accept(...)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/net/reverseconnection/listener.go:92
github.com/Symantec/Dominator/lib/net/reverseconnection.(*Listener).Accept(0xc42009e3c0, 0x8afb08, 0xc42001e0a0, 0x8e8c80, 0xc4201deff0)
	/home/vagrant/src/github.com/Symantec/Dominator/lib/net/reverseconnection/api.go:65 +0xc3
net/http.(*Server).Serve(0xc4201bbba0, 0x8e8400, 0xc42009e3c0, 0x0, 0x0)
	/home/vagrant/go/src/net/http/server.go:2770 +0x1a5
net/http.Serve(0x8e8400, 0xc42009e3c0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/net/http/server.go:2389 +0x73
created by github.com/Symantec/Dominator/sub/httpd.StartServer
	/home/vagrant/src/github.com/Symantec/Dominator/sub/httpd/api.go:31 +0x147

goroutine 13 [select, 2 minutes, locked to thread]:
runtime.gopark(0x8b0180, 0x0, 0x88fb11, 0x6, 0x18, 0x1)
	/home/vagrant/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc4201eaf50, 0xc42017e9c0)
	/home/vagrant/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/home/vagrant/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/home/vagrant/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 37 [chan receive, 2 minutes]:
github.com/Symantec/Dominator/sub/scanner.doDisableScanner(0xc400000001)
	/home/vagrant/src/github.com/Symantec/Dominator/sub/scanner/scand.go:71 +0x5b
github.com/Symantec/Dominator/sub/rpcd.(*rpcType).updateAndUnlock(0xc4200200e0, 0xc4200294e0, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc4201ee5a0, 0x3, 0x3, ...)
	/home/vagrant/src/github.com/Symantec/Dominator/sub/rpcd/update.go:70 +0xc1
created by github.com/Symantec/Dominator/sub/rpcd.(*rpcType).Update
	/home/vagrant/src/github.com/Symantec/Dominator/sub/rpcd/update.go:41 +0x295

rax    0xca
rbx    0xb07f60
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xb080a8
rsi    0x0
rbp    0x7ffe74f9b5d0
rsp    0x7ffe74f9b588
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xffffffffffffffff
r13    0x4
r14    0x3
r15    0x38
rip    0x459b51
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
$
```

State of the root tree (at `/test`):

```
$ sudo find /test
/test
/test/.subd
/test/.subd/root
/test/.subd/tmp
/test/.subd/tmp/fsbench
/test/.subd/tmp/fsbench/801
/test/.subd/objects
/test/.subd/objects/2f
/test/.subd/objects/2f/7d
/test/.subd/objects/2f/7d/83709aef0716b3e191d9db08a4e6c3a3170b8acdd771ed3d49c1c101a9295923d548396a0765eedf19e2fe8e00ee28d197c4eaadd407eb52be6b18dfc4ea
/test/.subd/objects/81
/test/.subd/objects/81/38
/test/.subd/objects/81/38/1f1dacd4824a6c503fd07057763099c12b8309d0abcec4000c9060cbbfa67988b2ada669ab4837fcd3d4ea6e2b8db2b9da9197d5112fb369fd006da545de
$
```

**Comment by rgooch** [comment]
That's odd. I've never seen that. Can you reproduce this without the change to deal with the previous issue (subd chewing up CPU when scanning a small file-system)?

**Comment by masiulaniec** [comment]
I've reverted that diff but the hang still reproes.

**Comment by rgooch** [comment]
Oh. Your root tree is empty, except for the stuff under `.subd`. I think I see what's going on. I've pushed https://github.com/rgooch/Dominator/commit/99bf2c239f23a4d3f4cd3bb65f7ebbdd11e805aa which should fix this. Please try it out.

**Comment by masiulaniec** [comment]
Nicely done, that fixes it.

**Comment by rgooch** [comment]
Fixed in PR# 422.
